### PR TITLE
Onboard dependabot workflows

### PR DESCRIPTION
**Pull request by purple-team-service-user**
Generated by https://github.com/adevinta/vulcan-cicd/actions/runs/6183978346

### CODE REVIEW

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185181895

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185212057

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185221659

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185261870

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185343192

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185382066

**Review by manelmontilla — APPROVED** [review]
LGTM

**Review by manelmontilla — APPROVED** [review]
LGTM

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6225233410

**Review by manelmontilla — APPROVED** [review]
LGTM

**Pull request merged**
